Allow templates from all namespaces to be processed
RedHatQE/openshift-python-wrapper pull request #1003
Opened 2022-12-06 20:54 UTC by RoniKishner

##### Short description:
Change the API call of processedtemplates to the current template namespace
##### More details:
The previous call used "openshift" namespace only, this change allow a template from any namespace to be processed

2022-12-06 20:58 UTC, RoniKishner commented
!Verified

2022-12-07 07:08 UTC, myakove requested changes

2022-12-07 07:08 UTC, myakove commented on ocp_resources/template.py
>          # TODO: remove after fix - https://issues.redhat.com/browse/KNIP-1055 (bug 1753554)
Can we remove the TODO? I see that the RFE is closed.

2022-12-07 08:34 UTC, RoniKishner commented
!Verified

2022-12-07 09:13 UTC, myakove approved these changes

2022-12-07 09:13 UTC, myakove commented
!NEED-REBASE

2022-12-07 09:32 UTC, myakove commented
test

2022-12-07 09:35 UTC, myakove commented
!-NEED_REBASE

2022-12-07 09:36 UTC, myakove commented
-!NEED_REBASE

2022-12-07 09:38 UTC, myakove commented
!-NEED-REBASE

2022-12-07 09:39 UTC, myakove approved these changes

2022-12-07 10:00 UTC, RoniKishner commented
!Verified

2022-12-07 10:03 UTC, myakove commented
@rnetser Please review

2022-12-07 12:23 UTC, rnetser approved these changes

2022-12-07 12:23 UTC, merged

2022-12-28 08:57 UTC, RoniKishner commented
!cherry-pick v4.12