VMExport: add status Ready, remove token required
RedHatQE/openshift-python-wrapper pull request #1048
Opened 2022-12-27 17:44 UTC by jpeimer

##### Short description:
- Add VirtualMachineExport.Status.READY
- Remove token_secret_ref as the required field (devs changed it to be optional)

2022-12-27 17:46 UTC, jpeimer commented
!verified

2022-12-29 07:27 UTC, myakove approved these changes

2022-12-29 07:27 UTC, myakove commented on ocp_resources/virtual_machine_export.py
> +            raise ValueError("source_kind and source_name or a yaml_file is required")
```
 if not (source_kind and source_name) and not yaml_file:
            raise ValueError("source_kind and source_name or a yaml_file is required")
```

Please move it inside `to_dict` after `if not self.yaml_file:`

2022-12-29 07:27 UTC, myakove commented
`Remove token_secret_ref as the required field (devs changed it to be optional)`
Is this changed for 4.12 or 4.13?

2022-12-29 07:28 UTC, myakove requested changes
Check my comments

2022-12-29 08:17 UTC, rnetser requested changes

2022-12-29 08:17 UTC, rnetser commented on ocp_resources/virtual_machine_export.py
> +    class Status(NamespacedResource.Status):
Please put under Resource.Status and use remove from Node.Status

2022-12-29 08:38 UTC, jpeimer commented
> `Remove token_secret_ref as the required field (devs changed it to be optional)` Is this changed for 4.12 or 4.13?
For both 4.12 and 4.13

2022-12-29 08:41 UTC, jpeimer commented
!verified

2022-12-29 14:21 UTC, rnetser approved these changes

2023-01-01 15:53 UTC, myakove approved these changes

2023-01-01 15:53 UTC, merged

2023-01-01 15:56 UTC, jpeimer commented
!cherry-pick v4.12