Return from nncp_wait_for_configuration if configured successfully
RedHatQE/openshift-python-wrapper pull request #1057
Opened 2023-01-10 17:08 UTC by Anatw

Refactor wait_for_confinuration_conditions_unknown_or_progressing to return if nncp is already configured successfully. It can happen that when debugging, a nncp is configured successfully, but an assert raises if we get into wait_for_configuration_conditions_unknown_or_progressing after the nncp was already configured successfully.

Signed-off-by: Anat Wax <awax@redhat.com>

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2023-01-10 17:08 UTC, Anatw commented
!verified

2023-01-10 17:10 UTC, Anatw commented
!verified

2023-01-11 09:54 UTC, myakove requested changes

2023-01-11 09:54 UTC, myakove commented on ocp_resources/node_network_configuration_policy.py
> +        if (
This function wait for unknown_or_progressing
it doesn't make sense to return when SUCCESSFULLY_CONFIGURED

2023-01-12 06:35 UTC, rnetser requested changes

2023-01-12 06:35 UTC, rnetser commented on ocp_resources/node_network_configuration_policy.py
> +            and self.status == self.Conditions.Reason.SUCCESSFULLY_CONFIGURED
if you change nncp, this may exit before configuration changes started and may end up not waiting for the config to start

2023-04-03 10:45 UTC, myakove commented
Please reopen if needed.

2023-04-03 10:45 UTC, closed without merging