virt-launcher: Switch to virtqemud id machine type has rhel9
RedHatQE/openshift-python-wrapper pull request #1096
Opened 2023-02-06 11:33 UTC by akri3i

Signed-off-by: akriti gupta <akrgupta@redhat.com>

##### Short description:

##### More details:

##### What this PR does / why we need it:
This PR update Virt Launcher Pod Hypervisor Connection URI socket to /var/run/libvirt/virtqemud-sock if machine type has rhel9 
https://github.com/kubevirt/kubevirt/pull/8619

##### Release note:

> virt-launcher: use `virtqemud` daemon instead of `libvirtd` if machine type is rhel9

2023-02-06 11:53 UTC, rnetser requested changes
Please also update the title, this PR also changes the behavior when `self.is_virt_launcher_pod_root`

2023-02-06 11:53 UTC, rnetser commented on ocp_resources/virtual_machine_instance.py
> +                )
```suggestion
           socket = "virtqemud" if "rhel9" in self.xml_dict["domain"]["os"]["@machine"] else "libvirt"
            hypervisor_connection_uri = f"-c qemu+unix:///session?socket=/var/run/libvirt/l{socket}-sock"
```

2023-02-07 08:43 UTC, akri3i commented on ocp_resources/virtual_machine_instance.py
> +                )
```suggestion
            socket = "virtqemud" if "rhel9" in self.xml_dict["domain"]["os"]["@machine"] else "libvirt"
            hypervisor_connection_uri = f"-c qemu+unix:///session?socket=/var/run/libvirt/{socket}-sock"
```

2023-02-07 09:04 UTC, myakove approved these changes

2023-02-08 07:48 UTC, rnetser approved these changes

2023-02-09 11:48 UTC, rnetser approved these changes

2023-02-09 11:57 UTC, akri3i commented
!verified

2023-02-09 11:58 UTC, akri3i commented
!verified

2023-02-09 12:48 UTC, kbidarkar commented
!-verified

2023-02-09 13:06 UTC, akri3i commented
!verified

2023-02-09 13:09 UTC, kbidarkar commented
LGTM

2023-02-09 13:28 UTC, myakove requested changes

2023-02-09 13:28 UTC, myakove commented on ocp_resources/virtual_machine_instance.py
> +                "virtqemud"
please save `virtqemud` and reuse.

2023-02-10 11:00 UTC, akri3i commented
!verified

2023-02-12 06:25 UTC, myakove approved these changes

2023-02-12 16:26 UTC, rnetser approved these changes

2023-02-12 16:26 UTC, merged

2023-02-13 10:23 UTC, kbidarkar commented
!cherry-pick v4.13

2023-02-13 10:24 UTC, kbidarkar commented
!cherry-pick v4.12