Add Grafana resources
RedHatQE/openshift-python-wrapper pull request #1121
Opened 2023-02-21 12:17 UTC by sarahbx

##### Short description:

Add Grafana Resources for grafana-operator
https://github.com/grafana-operator/grafana-operator/

2023-02-22 09:08 UTC, myakove requested changes

2023-02-22 09:08 UTC, myakove commented on ocp_resources/grafana.py
> +class Grafana(NamespacedResource):
Empty class without to_dict implement required is not allowed.
Please introduce to_dict().

2023-02-22 09:08 UTC, myakove commented on ocp_resources/grafana_data_source.py
> +class GrafanaDataSource(NamespacedResource):
Empty class without to_dict implement required is not allowed.
Please introduce to_dict().

2023-02-22 09:08 UTC, myakove commented on ocp_resources/grafana_dashboard.py
> +        self.label = label
All of those required? Please add verification for required args under `if not self.yaml_file:`

2023-03-29 19:11 UTC, sarahbx commented
on hold due to recent release of v5 which altered the specs of the resources.

2023-06-07 08:44 UTC, myakove commented
test

2023-08-05 02:08 UTC, closed without merging