Adding new fields selector.matchLabels.pvLabel under spec of pvc
RedHatQE/openshift-python-wrapper pull request #1151
Opened 2023-03-21 18:27 UTC by akri3i

##### Short description:
To configure pvLable while crteating PersistentVolumeClaim adding new fields selector.matchLabels.pvLabel under spec of pvc yaml 
##### More details:

##### What this PR does / why we need it:
pvLable field is currently not configurable while creating PersistentVolumeClaim, this patch add the variable pvLable under spec.selector.matchLabelsto make it configurable directly 
##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2023-03-21 18:27 UTC, akri3i commented
!verified

2023-03-22 09:28 UTC, myakove requested changes

2023-03-22 09:28 UTC, myakove commented on ocp_resources/persistent_volume_claim.py
> +        self.pvLabel = pvlabel
`pvLabel` please rename to python naming `pvlabel`

2023-03-22 10:09 UTC, akri3i commented
/verified

2023-03-22 11:03 UTC, rnetser approved these changes

2023-03-23 08:46 UTC, myakove approved these changes

2023-03-23 08:46 UTC, merged

2023-03-29 08:37 UTC, akri3i commented
!cherry-pick v4.13

2023-03-29 08:44 UTC, akri3i commented
/cherry-pick v4.13