ResourceEditor: ResourceField sanitizing
RedHatQE/openshift-python-wrapper pull request #118
Opened 2021-08-23 18:52 UTC by obaireys

Added a static method to ResourceEditor which recursively turns
ResourceField objects into dicts to avoid issues when applying patches
created by appending/changing existing resource fields.

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2021-08-24 09:56 UTC, myakove commented
/apporve

2021-08-24 12:52 UTC, rnetser requested changes

2021-08-24 12:52 UTC, rnetser commented on ocp_resources/resource.py
> +        elif type(res) == dict:
```suggestion
        elif isinstance(res, dict):
```

2021-08-24 12:52 UTC, rnetser commented on ocp_resources/resource.py
> +        elif type(res) == list:
use isinstance

2021-08-24 12:52 UTC, rnetser commented on ocp_resources/resource.py
> +        else:
The `else` is redundant; can just return res

2021-08-25 07:03 UTC, rnetser commented
/approve

2021-08-25 16:40 UTC, obaireys commented on ocp_resources/resource.py
> +        if issubclass(type(res), ResourceField):
I would prefer to cover the case where some subclass of `ResourceField` for some specific resource type, as opposed to the primitives `list` and `dict` whose use is independent of `ResourceField`.

2021-09-01 14:20 UTC, obaireys commented
/verified

2021-09-02 08:02 UTC, rnetser commented
/approve

2021-09-02 08:07 UTC, rnetser approved these changes

2021-09-02 08:07 UTC, merged