Add label parameter to resource + namespace + data_source
RedHatQE/openshift-python-wrapper pull request #1192
Opened 2023-04-18 08:27 UTC by RoniKishner

##### Short description:
Add label parameter to resource, namespace and DataSource classes

##### More details:
- Added label parameter to Resource object so it will be added to the resource manifest under metadata->labels
- Changed namespace.py so it will use the new label parameter in Resource object
- Added label parameter to DataSource object

##### What this PR does / why we need it:
Label field is relevant to all resources, this will enable easier use of creating a resource with labels.
Also made changes to Namespace + DataSource so they will use the label parameter 

##### Which issue(s) this PR fixes:
Enable use of label when creating a new DataSource

2023-04-18 09:07 UTC, RoniKishner commented
/verified

2023-04-19 11:15 UTC, rnetser requested changes

2023-04-19 11:15 UTC, rnetser commented on ocp_resources/data_source.py
> +        label=None,
either you add it to all resources or do not add it as we already have `kwargs` which are passed.

2023-04-19 13:53 UTC, RoniKishner commented
/verified

2023-04-20 11:10 UTC, rnetser approved these changes

2023-04-20 11:11 UTC, rnetser requested changes
Please update the title and description to match the updated code

2023-04-23 08:14 UTC, rnetser approved these changes

2023-04-23 09:38 UTC, omrirh commented
/lgtm

2023-04-23 09:40 UTC, myakove approved these changes

2023-04-23 09:41 UTC, merged

2023-04-24 07:35 UTC, RoniKishner commented
/cherry-pick v4.12

2023-04-24 07:36 UTC, RoniKishner commented
/cherry-pick v4.13