fix inheritence for resources
RedHatQE/openshift-python-wrapper pull request #121
Opened 2021-08-24 15:21 UTC by ibesso-rh

##### Short description:
Correcting inheritence to certain resources

##### More details:

##### What this PR does / why we need it:
tests requires this to fetch those resources, which is currently not possible.

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:
release.sh was fixed by pre-commit

##### Bug:

2021-08-24 15:21 UTC, ibesso-rh commented
/verified

2021-08-24 15:26 UTC, rnetser requested changes

2021-08-24 15:26 UTC, rnetser commented on release.sh
> +git checkout $MASTER_BRANCH
please rebase

2021-08-24 16:18 UTC, ibesso-rh commented on release.sh
> +git checkout $MASTER_BRANCH
done

2021-08-25 07:02 UTC, rnetser commented
/approve

2021-08-25 08:08 UTC, myakove commented
/approve

2021-08-28 09:23 UTC, ibesso-rh commented
@myakove , @rnetser , for some reason, the checklist still show "Pending - needs aprove from maintainers". could you please re-approve or check what was wrong?

2021-08-28 10:59 UTC, myakove commented
@ofirnash1 please review

2021-08-28 19:32 UTC, ofirnash1 commented
/lgtm

2021-08-28 19:34 UTC, merged