adding a restartCount class to resource
RedHatQE/openshift-python-wrapper pull request #1534
Opened 2023-12-03 14:54 UTC by Ahmad-Hafe

##### Short description:
I'm adding a new class to ocp_resources/resource.py 

##### More details:
I need to track resource.instance.status.restartCount  which is not applied to the wrapper 

##### What this PR does / why we need it:
to get easy access to instance.status.restartCount 

##### Which issue(s) this PR fixes:
None
##### Special notes for reviewer:
None
##### Bug:
None

2023-12-04 09:40 UTC, myakove commented on ocp_resources/resource.py
> +        class restartCount:
If it's more than one resource, it is OK to have it here (the other option is to have duplicates on multiple resources).

@Ahmad-Hafe which resources have `restartCount` ?

2023-12-04 22:39 UTC, dbasunag commented on ocp_resources/resource.py
> +        class restartCount:
I think only pods/containers have restartCount. @Ahmad-Hafe is there any other resources?

2023-12-04 23:14 UTC, jpeimer commented on ocp_resources/resource.py
> +        class restartCount:
and DataVolumes

2023-12-06 07:54 UTC, rnetser requested changes

2023-12-06 07:54 UTC, rnetser commented on ocp_resources/resource.py
> +        class restartCount:
iiuc what you need, to get `instance.status.restartCount` should be a property and not a class

2023-12-07 15:55 UTC, Ahmad-Hafe commented on ocp_resources/resource.py
> +        class restartCount:
it can be a class as well, that is the discussion here

2024-01-22 02:12 UTC, closed without merging