Adding support for fenceAgentRemediationTemplate
RedHatQE/openshift-python-wrapper pull request #1869
Opened 2024-06-06 00:39 UTC by geetikakay

##### Short description:
support for fenceAgentRemediationTemplate
##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2024-06-06 09:53 UTC, omrirh commented on ocp_resources/fence_agent_remediation_templates.py
> +# API Reference: https://github.com/medik8s/fence-agents-remediation
Please move to class docstring

2024-06-12 16:39 UTC, geetikakay commented
@myakove Hi , pre-commit fails . That's how timeout should be : https://github.com/medik8s/fence-agents-remediation/blob/main/api/v1alpha1/fenceagentsremediation_types.go#L80

2024-06-13 07:10 UTC, myakove requested changes

2024-06-13 07:10 UTC, myakove commented on ocp_resources/fence_agent_remediation_templates.py
> +        timeout: Optional[str] = None,
Resource already have timeout, you need to set here different name.

2024-06-13 08:28 UTC, myakove submitted a review, later dismissed

2024-06-13 08:34 UTC, geetikakay commented
/verified

2024-06-13 08:34 UTC, rnetser requested changes

2024-06-13 08:34 UTC, rnetser commented on ocp_resources/fence_agent_remediation_templates.py
> +            if self.retry_count != 0:
```suggestion
            if self.retry_count is not None:
```

the API does value validation

2024-06-13 08:34 UTC, rnetser commented on ocp_resources/fence_agent_remediation_templates.py
> +        self.shared_parameters = shared_parameters or {}
no need to set to an empty dict

2024-06-13 08:34 UTC, rnetser commented on ocp_resources/fence_agent_remediation_templates.py
> +        self.node_parameters = node_parameters or {}
ditto

2024-06-13 10:33 UTC, geetikakay commented
/verified

2024-06-16 08:01 UTC, rnetser requested changes

2024-06-16 08:01 UTC, rnetser commented on ocp_resources/fence_agent_remediation_templates.py
> +            agent (str): The name of the fence agent to use, must start with "fence_".
```suggestion
            agent (str): The name of the fence agent to use.
```

this is a constraint done by the API, not the wrapper code. please remove from docsring

2024-06-17 13:39 UTC, geetikakay commented
/verified

2024-06-18 09:44 UTC, geetikakay commented
/verified

2024-06-18 10:37 UTC, rnetser approved these changes

2024-06-19 09:15 UTC, geetikakay commented
@myakove @rnetser Hello, can this be merged. Thanks

2024-06-20 06:29 UTC, merged