Add new entry to Resource.ApiGroup for Infra features
RedHatQE/openshift-python-wrapper pull request #210
Opened 2021-10-10 19:44 UTC by dbasunag

##### Short description:
Based on review comment in a cnv-tests PR adding an entry of operators.openshift.io/infrastructure-features to Resource.ApiGroup
##### More details:
As suggested by @rnetser in a cnv-tests PR, adding this entry
##### What this PR does / why we need it:
This would be used in tests
##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2021-10-11 04:04 UTC, myakove commented on ocp_resources/resource.py
> +        INFRA_FEATURES = "operators.openshift.io/infrastructure-features"
this is not match our code, you should add only "operators.openshift.io" here
name should end with _IO and should be placed in the right line (a, b, c ....)

2021-10-11 16:09 UTC, myakove requested changes

2021-10-11 16:09 UTC, myakove commented on ocp_resources/resource.py
> +        INFRA_FEATURES_IO = "operators.openshift.io"
please move it to the right place (ordered by abc)

2021-10-11 17:00 UTC, dbasunag commented on ocp_resources/resource.py
> +        INFRA_FEATURES_IO = "operators.openshift.io"
Done

2021-10-11 18:56 UTC, myakove commented on ocp_resources/resource.py
> +        OPERATORS_OPENSHIFT_IO = "operators.openshift.io"
Move it after `OPERATORS_COREOS_COM` please.

2021-10-12 15:46 UTC, dbasunag commented
/verified

2021-10-13 04:42 UTC, merged