Added support for maxUnavailable
RedHatQE/openshift-python-wrapper pull request #265
Opened 2021-12-06 23:38 UTC by geetikakay

Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>

##### Short description:
Support for maxunavailable for node network configuration policy
##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2021-12-07 09:36 UTC, rnetser requested changes

2021-12-07 09:36 UTC, rnetser commented on ocp_resources/node_network_configuration_policy.py
> +            res["spec"]["maxUnavailable"] = self.max_unavailable
res.setdefault("spec", {})....

2021-12-07 18:13 UTC, geetikakay commented on ocp_resources/node_network_configuration_policy.py
> +            res["spec"]["maxUnavailable"] = self.max_unavailable
ack @rnetser

2021-12-08 08:33 UTC, myakove commented
Please update the commit msg, support for which resource.

2021-12-08 08:33 UTC, myakove commented
and rebase please.

2021-12-09 06:40 UTC, myakove commented
/approve

2021-12-09 09:34 UTC, rnetser commented
/approve

2021-12-10 11:49 UTC, geetikakay commented
@myakove @rnetser please review. I have  fixed tox failures.

2021-12-10 12:20 UTC, myakove commented
/approve

2021-12-10 12:31 UTC, geetikakay commented
/verified

Verified in downstream patch as dependency

2021-12-10 12:32 UTC, geetikakay commented
Verified in downstream patch as dependency

2021-12-10 13:23 UTC, myakove commented
> Verified in downstream patch as dependency

thanks, No need to mention d/s here :)

2021-12-10 13:23 UTC, merged