Allow ipv6 config
RedHatQE/openshift-python-wrapper pull request #333
Opened 2022-01-04 15:02 UTC by AdiZav

Allow ipv6 configuration of node ifaces.
Currently, only enabling/disabling ipv6 is allowed

2022-01-04 20:19 UTC, myakove submitted a review, later dismissed

2022-01-05 16:31 UTC, rnetser requested changes

2022-01-05 16:31 UTC, rnetser commented on ocp_resources/node_network_configuration_policy.py
>          self.ipv6_enable = ipv6_enable
please place all ipv6 parameters together

2022-01-06 14:02 UTC, AdiZav commented
/verified

2022-01-06 14:09 UTC, myakove approved these changes

2022-01-06 14:12 UTC, rnetser approved these changes

2022-01-06 14:12 UTC, merged