Allow ifaces update
RedHatQE/openshift-python-wrapper pull request #356
Opened 2022-01-11 15:57 UTC by AdiZav

Fix adding ifaces to res

2022-01-11 16:10 UTC, myakove requested changes

2022-01-11 16:12 UTC, AdiZav commented on ocp_resources/node_network_configuration_policy.py
> +            self.desired_state
ack

2022-01-11 16:49 UTC, rnetser approved these changes

2022-01-12 09:21 UTC, myakove approved these changes

2022-01-12 09:21 UTC, merged