Add Failing condition (#483)
RedHatQE/openshift-python-wrapper pull request #505
Opened 2022-04-15 01:37 UTC by dbasunag

##### Short description: Cherry-pick of https://github.com/RedHatQE/openshift-python-wrapper/pull/483

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2022-04-16 08:02 UTC, myakove requested changes

2022-04-16 08:02 UTC, myakove commented on CHANGELOG.md
> -null
This file shouldn't be changed as part of this PR.

2022-04-18 12:18 UTC, myakove approved these changes

2022-04-18 12:19 UTC, dbasunag commented
!verified

2022-04-18 12:19 UTC, merged