Add client to ClusterRoleBinding __init__
RedHatQE/openshift-python-wrapper pull request #565
Opened 2022-05-25 11:51 UTC by jpeimer

##### Short description:
Add client to ClusterRoleBinding __init__

2022-05-25 11:52 UTC, jpeimer commented
!verified

2022-05-25 12:48 UTC, myakove requested changes

2022-05-25 12:48 UTC, myakove commented on ocp_resources/cluster_role_binding.py
> +        client=None,
Please add **kwargs, and add **kwargs to super() call.

2022-05-25 12:48 UTC, myakove commented on ocp_resources/cluster_role_binding.py
>          super().__init__(name=name)
`super().__init__(name=name, **kwargs)`

2022-05-25 13:36 UTC, jpeimer commented
!verified

2022-05-26 08:38 UTC, myakove approved these changes

2022-05-26 08:41 UTC, jpeimer commented
!verified

2022-05-26 08:43 UTC, merged