Move kube_v1_api to separate method
RedHatQE/openshift-python-wrapper pull request #605
Opened 2022-06-01 13:00 UTC by sarahbx

Reducing the number of attributes that must be handled
to serialize resources

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2022-06-01 18:49 UTC, dbasunag requested changes

2022-06-01 18:49 UTC, dbasunag commented on ocp_resources/pod.py
> +    def _get_kube_v1_api(self):
This should be moved to resource.py, that way it could be reused here as well as in _collect_pod_logs()

2022-06-05 08:55 UTC, myakove requested changes

2022-06-05 08:55 UTC, myakove commented on ocp_resources/pod.py
> +
can be property

2022-06-06 07:27 UTC, myakove approved these changes

2022-06-06 12:26 UTC, dbasunag approved these changes

2022-06-23 18:00 UTC, rnetser approved these changes

2022-07-05 15:53 UTC, dshchedr approved these changes

2022-07-06 07:41 UTC, rnetser commented
!verified

2022-07-06 07:42 UTC, merged