Allow creating jobs
RedHatQE/openshift-python-wrapper pull request #612
Opened 2022-06-08 12:49 UTC by AdiZav

##### Short description:
Allow creating jobs with minimal config
##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2022-06-08 12:56 UTC, myakove submitted a review, later dismissed

2022-06-08 14:38 UTC, sarahbx approved these changes

2022-06-09 07:28 UTC, rnetser commented on ocp_resources/job.py
> +            self.res["spec"]["template"]["spec"]["containers"] = self.containers
as this always happens, for readability - move under the definition of template.spec.

2022-06-16 10:57 UTC, AdiZav commented
!verifired

2022-06-16 11:29 UTC, myakove requested changes

2022-06-16 11:29 UTC, myakove commented on ocp_resources/job.py
> +        if self.backoff_limit or self.backoff_limit == 0:
```suggestion
        if self.backoff_limit is not None:
```

2022-06-20 08:50 UTC, AdiZav commented
!verified

2022-06-20 11:45 UTC, AdiZav commented on ocp_resources/job.py
> +        if self.backoff_limit or self.backoff_limit == 0:
Resolved

2022-06-20 12:44 UTC, myakove approved these changes

2022-06-20 12:45 UTC, merged