Add APIServer resource
RedHatQE/openshift-python-wrapper pull request #824
Opened 2022-09-19 18:02 UTC by yossisegev

Needed for the cluster-wide crypto policy epic (https://issues.redhat.com/browse/CNV-14819)

2022-09-20 05:22 UTC, rnetser requested changes
This repo is not tied to openshift virtualization; please update the description (ie should not point to any cnv-related epics)

2022-09-20 07:05 UTC, yossisegev commented
!verified

2022-09-20 07:19 UTC, rnetser approved these changes

2022-09-20 07:19 UTC, merged

2022-10-02 08:55 UTC, yossisegev commented
!cherry-pick v4.12