Add conditions_sampler function for resource
RedHatQE/openshift-python-wrapper pull request #826
Opened 2022-09-20 08:22 UTC by myakove

##### Short description:
Introduce conditions_sampler function to get all resource conditions.

2022-09-20 08:40 UTC, myakove commented
!verified

2022-09-20 08:46 UTC, rnetser commented on ocp_resources/resource.py
> +    def conditions_sampler(self, timeout):
Gets the resource not specifically `conditions` - should either be renamed or change what is yielded

2022-09-20 09:00 UTC, rnetser requested changes
.

2022-09-21 08:09 UTC, myakove commented
!verified

2022-09-28 08:17 UTC, rnetser approved these changes

2022-09-28 08:20 UTC, rnetser approved these changes

2022-10-27 11:46 UTC, rnetser submitted a review, later dismissed

2022-11-16 17:03 UTC, myakove commented
!verified

2022-11-23 07:42 UTC, rnetser approved these changes

2022-11-27 10:51 UTC, myakove commented
!verified

2022-11-27 10:53 UTC, merged

2022-11-27 10:53 UTC, myakove commented
!cherry-pick v4.12