Fix add_rule in ClusterRole
RedHatQE/openshift-python-wrapper pull request #828
Opened 2022-09-20 13:23 UTC by myakove

Add_rule we override by to_dict if the no rule was passed when initializing the resource

2022-09-20 13:35 UTC, rnetser requested changes

2022-09-20 13:35 UTC, rnetser commented on ocp_resources/cluster_role.py
> +        verbs,
`if verbs:` should be removed (line 68)

2022-09-21 08:09 UTC, myakove commented
!verified

2022-09-21 13:35 UTC, rnetser approved these changes

2022-09-21 13:35 UTC, merged

2022-09-22 06:43 UTC, myakove commented
!cherry-pick v4.12