add machineset resource implementation
RedHatQE/openshift-python-wrapper pull request #83
Opened 2021-08-04 07:39 UTC by GuyAfik

This patch adds the machineset resource.
The purpose of this patch is to allow endpoint users to be able to
create machineset resource on OpenShift.

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

##### Release notes:

```release-note

```

2021-08-04 07:43 UTC, myakove requested changes

2021-08-04 07:43 UTC, myakove commented on ocp_resources/machineset.py
> +        return self.instance.status['availableReplicas']
Please access the val directly

self.instance.status.availableReplicas

2021-08-04 10:05 UTC, myakove approved these changes

2021-08-08 16:43 UTC, myakove commented
@GuyAfik Do you need any help with this PR?

2021-08-09 07:41 UTC, GuyAfik commented
> @GuyAfik Do you need any help with this PR?

Yes I have problems with the pre-commit from some reason

Im failing on that error when running 'pre-commit run --all-files' which is why the ci fails.
I am not quite sure why after digging in the internet for a while.

looks like its trying to checkout into a branch that does not exist.


[INFO] Initializing environment for https://github.com/hadialqattan/pycln.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '0.0.1-beta.1')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec '0.0.1-beta.1' did not match any file(s) known to git

2021-08-09 08:27 UTC, myakove commented
> > @GuyAfik Do you need any help with this PR?
> 
> Yes I have problems with the pre-commit from some reason
> 
> Im failing on that error when running 'pre-commit run --all-files' which is why the ci fails.
> I am not quite sure why after digging in the internet for a while.
> 
> looks like its trying to checkout into a branch that does not exist.
> 
> [INFO] Initializing environment for https://github.com/hadialqattan/pycln.
> An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '0.0.1-beta.1')
> return code: 1
> expected return code: 0
> stdout: (none)
> stderr:
> error: pathspec '0.0.1-beta.1' did not match any file(s) known to git

Please rebase your code, it was fixed.

2021-08-09 10:12 UTC, GuyAfik commented
> > > @GuyAfik Do you need any help with this PR?
> > 
> > 
> > Yes I have problems with the pre-commit from some reason
> > Im failing on that error when running 'pre-commit run --all-files' which is why the ci fails.
> > I am not quite sure why after digging in the internet for a while.
> > looks like its trying to checkout into a branch that does not exist.
> > [INFO] Initializing environment for https://github.com/hadialqattan/pycln.
> > An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '0.0.1-beta.1')
> > return code: 1
> > expected return code: 0
> > stdout: (none)
> > stderr:
> > error: pathspec '0.0.1-beta.1' did not match any file(s) known to git
> 
> Please rebase your code, it was fixed.

ack, I will try, thanks!

2021-08-09 13:05 UTC, closed without merging

2021-08-09 13:06 UTC, GuyAfik commented
I will push a new PR with some extra code