cherry-pick to V4.9: Storage: fix snapshot resources
RedHatQE/openshift-python-wrapper pull request #913
Opened 2022-11-02 10:11 UTC by FuhuiYang14

* Storage: fix snapshot resources

  Restore status complete and snapshot status readyToUse are not enough to determine that the restore/snapshot are done. Added a function that takes the VM status in consideration as well

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2022-11-08 08:09 UTC, myakove requested changes

2022-11-08 08:09 UTC, myakove commented on ocp_resources/constants.py
> +TIMEOUT_1MINUTE = 60
where this is used?

2022-11-14 08:34 UTC, myakove approved these changes

2022-11-14 08:36 UTC, merged

2022-11-14 08:43 UTC, FuhuiYang14 commented
!cherry-pick v4.8

2022-11-30 09:29 UTC, FuhuiYang14 commented
!cherry-pick v4.8