rename all res to self.res
RedHatQE/openshift-python-wrapper pull request #945
Opened 2022-11-03 12:46 UTC by myakove

Rename all res to self.res to be consistent with the code.

2022-11-04 13:28 UTC, rnetser commented on ocp_resources/restore.py
> +        self.res = super().to_dict()
`self.res` be defined in __init__  (i.e not hide attributes)

2022-11-04 13:28 UTC, rnetser commented on ocp_resources/backup.py
> +        return self.res
now that is `self.res` is updated, do we still need to return it?

2022-11-07 10:42 UTC, myakove commented
!DO-NOT-MERGE

2022-11-11 10:41 UTC, myakove commented
!-DO-NOT-MERGE

2022-11-14 06:46 UTC, rnetser requested changes

2022-11-14 06:46 UTC, rnetser commented on ocp_resources/virtual_machine_import.py
> +        return self.res
can be removed

2022-11-14 06:46 UTC, rnetser commented on ocp_resources/virtual_machine_import.py
> +            return self.res
`if not self.yaml_file`

2022-11-14 10:40 UTC, myakove commented
!verified

2022-11-14 11:50 UTC, rnetser approved these changes

2022-11-14 11:51 UTC, myakove commented
!verified

2022-11-14 15:53 UTC, merged

2022-11-14 15:54 UTC, myakove commented
!cherry-pick v4.12

2022-11-14 16:49 UTC, myakove commented
!cherry-pick v4.12