Add Topolvm storage class and reorder the storage classes
RedHatQE/openshift-python-wrapper pull request #974
Opened 2022-11-15 08:01 UTC by jpeimer

##### Short description:
Add Topolvm storage class and reorder the storage classes in alphabetical order

##### More details:
Starting SNO 4.12, Topolvm is the default storage class that is being deployed by Assisted Installer

2022-11-15 15:48 UTC, jpeimer commented on ocp_resources/storage_class.py
> +        TOPOLVM = "odf-lvm-vg1"
We can give it any name, but this is the name that Assisted Installer is using

2022-11-16 14:27 UTC, myakove requested changes

2022-11-16 14:27 UTC, myakove commented on ocp_resources/storage_class.py
> +        TOPOLVM = "odf-lvm-vg1"
I think `class Types` should be removed from the wrapper as it can be any name

2022-11-17 12:44 UTC, myakove commented
@jpeimer can this be closed?

2022-11-17 12:56 UTC, jpeimer commented
Yes, closing this as we are moving the Storage Class Names to our test repo. Thanks!

2022-11-17 12:56 UTC, closed without merging