Add controller revision resource
RedHatQE/openshift-python-wrapper pull request #978
Opened 2022-11-17 13:35 UTC by RoniKishner

##### Short description:
Add controller revision resource to ocp_resources

##### More details:
controller revision is used to control and log the version (changed on edits) of the resource it is attached to

2022-11-17 13:58 UTC, RoniKishner commented
!verified

2022-11-17 14:31 UTC, myakove requested changes

2022-11-17 14:31 UTC, myakove commented on ocp_resources/controller_revision.py
> +class ControllerRevision(NamespacedResource):
Please include reference to the resource
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/controller-revision-v1/

Please implement under to_dict the required resource data.

2022-11-20 07:06 UTC, RoniKishner commented
!verified

2022-11-20 09:08 UTC, myakove requested changes

2022-11-20 09:08 UTC, myakove commented on ocp_resources/controller_revision.py
> +        self._base_body()
Please follow other resources example
```
super().to_dict()
if not self.yaml_file:
    <you code here>
```

2022-11-20 09:08 UTC, myakove commented on ocp_resources/controller_revision.py
> +        self.res["metadata"]["ownerReference"] = self.owner_references
You assign `self.owner_references` and `self.revision_object.res`  even if there are `None`

2022-11-20 09:08 UTC, myakove commented on ocp_resources/controller_revision.py
> +        self.res["metadata"]["ownerReference"] = self.owner_references
Use `self.res.setdefault` to update `self.res`

2022-11-20 13:26 UTC, RoniKishner commented
!verified

2022-11-21 08:16 UTC, myakove approved these changes

2022-11-21 08:24 UTC, RoniKishner commented
!cherry-pick v4.12

2022-11-21 09:00 UTC, rnetser approved these changes

2022-11-21 09:00 UTC, merged

2022-11-21 09:29 UTC, RoniKishner commented
!cherry-pick v4.12