override create() and deploy() for projectrequest
RedHatQE/openshift-python-wrapper pull request #996
Opened 2022-12-02 22:56 UTC by dbasunag

##### Short description: Need to override create() and deploy() call for project request, as, there is no wait for project request and if an unprivilegeduser is making a projectrequest post call, using the base class create() call would fail as `self.instance.metadata.resourceVersion` is not allowed by unprivileged user.

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2022-12-03 00:44 UTC, dbasunag commented
!verified

2022-12-05 06:18 UTC, rnetser requested changes

2022-12-05 06:18 UTC, rnetser commented on ocp_resources/project.py
> +    def deploy(self, wait=False):
this breaks using `skip_resource_kind_create_if_exists`

2022-12-05 06:18 UTC, rnetser commented on ocp_resources/project.py
> +        self.api.create(body=self.res, namespace=self.namespace, dry_run=self.dry_run)
duplicate code, please save and re-use

2022-12-05 08:15 UTC, myakove commented
Fixed by https://github.com/RedHatQE/openshift-python-wrapper/pull/998

2022-12-05 08:15 UTC, closed without merging